-- H2-compatible version of V1__create_task_schema.sql
-- This is used when running with H2 in test mode
-- Create table with CHECK constraint instead of ENUM (H2 compatible)
-- Using V1.1 to avoid conflict with main V1 migration
CREATE TABLE IF NOT EXISTS public.task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100),
    description VARCHAR(200),
    status VARCHAR(32) CHECK (
        status IN (
            'NEW',
            'PENDING',
            'IN_PROGRESS',
            'COMPLETED',
            'APPROVED',
            'CANCELLED'
        )
    ),
    duedate TIMESTAMP(6) WITHOUT TIME ZONE,
    tasknum INTEGER
);
-- Indexes
CREATE INDEX IF NOT EXISTS idx_task_status ON public.task(status);
CREATE INDEX IF NOT EXISTS idx_task_due ON public.task(duedate);